export const SELECTED_COURSSE_ID=process.env.SELECTED_COURSSE_ID || 100999
export const TIMEOUT=process.env.TIMEOUT || 5000 // 30 seconds
export const PREVIEW_BUTTON_HOVER_BGCOLOR=process.env.PREVIEW_BUTTON_HOVER_BGCOLOR || "rgb(65, 178, 148)"
export const RANDOM_RELATED_COURSE=process.env.RANDOM_RELATED_COURSE || 1
export const RANDOM_BLOG_POST=process.env.RANDOM_BLOG_POST || 1
export const RANDOM_FILTER_CATEGORY=process.env.RANDOM_FILTER_CATEGORY || 1
export const RANDOM_SUGGESTED_POST=process.env.RANDOM_SUGGESTED_POST || 1